# Generated by Django 3.0.8 on 2020-07-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PublishModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('authors', models.ManyToManyField(to='example.AuthorModel')),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.PublishModel')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telphone', models.IntegerField(max_length=11)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='example.AuthorModel')),
            ],
        ),
    ]
